name: Bots

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cache:
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    uses: johngeorgewright/workflows/.github/workflows/yarn-cache.yml@main

  yarn-sdk:
    needs: [cache]
    name: Rebuild Yarn SDKs
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.cache.outputs.key }}
          path: ${{ needs.cache.outputs.path }}

      - name: Update SDKs
        run: yarn dlx @yarnpkg/sdks

      - name: Commit
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .yarn

          if [[ $(git status --short) ]]
          then
            git commit -m "chore: rebuild yarn sdks"
            git push
          fi
