name: Pull Request

on:
  pull_request:

  workflow_call:
    outputs:
      cache-key:
        description: Cache key
        value: ${{ jobs.cache.outputs.key }}
      cache-path:
        description: Cache path
        value: ${{ jobs.cache.outputs.path }}

jobs:
  cache:
    uses: johngeorgewright/workflows/.github/workflows/yarn-cache.yml@main

  test:
    needs: [cache]
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.cache.outputs.key }}
          path: ${{ needs.cache.outputs.path }}

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
